name: bbml_draft
description: MLBB draft hero öneri asistanı (Flutter)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.4
  shared_preferences: ^2.3.2
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.4
  onesignal_flutter: ^5.1.3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  webview_flutter: ^4.7.0

  # Material localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/images/
    - assets/icons/
